language: python
python:
- "3.5"
- "3.6"
install:
- pip install .
script:
- pip install -U nose coverage
- nosetests --with-coverage --cover-package=symigrate/ --cover-xml test/
after_success:
- pip install coveralls
- coveralls