SYMIGRATE_MIGRATION_PREFIX = "V"
SYMIGRATE_MIGRATION_SEPARATOR = "__"
SYMIGRATE_MIGRATION_SUFFIX = None
SYMIGRATE_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%S"
SYMIGRATE_ENCODING = "utf-8"
SYMIGRATE_DEFAULT_SCOPE = "DEFAULT"
SYMIGRATE_MIGRATION_TIMEOUT = 5
SYMIGRATE_LOGGING_LEVEL = "INFO"
